apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
        - name: processor
          image: gcr.io/cloud-a3-454304/processor-service:latest
          ports:
            - containerPort: 7000
          volumeMounts:
            - name: shared-storage
              mountPath: /kirtan_PV_dir
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
spec:
  selector:
    app: processor
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: ClusterIP